@startuml

!includeurl https://raw.githubusercontent.com/denser-ru/plantuml/main/block_style.puml

alt Блок 1
!includeurl https://raw.githubusercontent.com/denser-ru/plantuml/main/block_1.puml
end

alt Блок 2
!includeurl https://raw.githubusercontent.com/denser-ru/plantuml/main/block_2.puml
end

@enduml