@startuml

participant "Шифровщик A" as crpt_a
participant "Узел А" as node_a
participant "Шлюз" as rt
participant "Узел B" as node_b
participant "Шифровщик B" as crpt_b

skinparam ParticipantBackgroundColor #909090
skinparam ParticipantBorderColor #303030

@enduml